export const BASE_ITEMS = {
  seq: [
    {
      id_bgroup: "2",
      name_bgroup: "Body Armours",
      max_affix: "6",
      is_rare: "1",
      is_influenced: "1",
      is_fossil: "1",
      is_ess: "1",
      is_craftable: "1",
      is_notable: "0",
      is_catalyst: "0",
      has_items: "1",
      max_sockets: "0",
    },
    {
      id_bgroup: "3",
      name_bgroup: "Boots",
      max_affix: "6",
      is_rare: "1",
      is_influenced: "1",
      is_fossil: "1",
      is_ess: "1",
      is_craftable: "1",
      is_notable: "0",
      is_catalyst: "0",
      has_items: "1",
      max_sockets: "0",
    },
    {
      id_bgroup: "12",
      name_bgroup: "Cluster Jewels",
      max_affix: "4",
      is_rare: "1",
      is_influenced: "0",
      is_fossil: "1",
      is_ess: "0",
      is_craftable: "0",
      is_notable: "1",
      is_catalyst: "0",
      has_items: "0",
      max_sockets: "0",
    },
    {
      id_bgroup: "19",
      name_bgroup: "Fishing Rods",
      max_affix: "6",
      is_rare: "1",
      is_influenced: "0",
      is_fossil: "0",
      is_ess: "0",
      is_craftable: "0",
      is_notable: "0",
      is_catalyst: "0",
      has_items: "1",
      max_sockets: "0",
    },
    {
      id_bgroup: "10",
      name_bgroup: "Flasks",
      max_affix: "2",
      is_rare: "0",
      is_influenced: "0",
      is_fossil: "0",
      is_ess: "0",
      is_craftable: "1",
      is_notable: "0",
      is_catalyst: "0",
      has_items: "0",
      max_sockets: "0",
    },
    {
      id_bgroup: "5",
      name_bgroup: "Gloves",
      max_affix: "6",
      is_rare: "1",
      is_influenced: "1",
      is_fossil: "1",
      is_ess: "1",
      is_craftable: "1",
      is_notable: "0",
      is_catalyst: "0",
      has_items: "1",
      max_sockets: "0",
    },
    {
      id_bgroup: "13",
      name_bgroup: "Heist",
      max_affix: "4",
      is_rare: "1",
      is_influenced: "0",
      is_fossil: "1",
      is_ess: "0",
      is_craftable: "0",
      is_notable: "0",
      is_catalyst: "0",
      has_items: "0",
      max_sockets: "0",
    },
    {
      id_bgroup: "4",
      name_bgroup: "Helmets",
      max_affix: "6",
      is_rare: "1",
      is_influenced: "1",
      is_fossil: "1",
      is_ess: "1",
      is_craftable: "1",
      is_notable: "0",
      is_catalyst: "0",
      has_items: "1",
      max_sockets: "0",
    },
    {
      id_bgroup: "20",
      name_bgroup: "Idols",
      max_affix: "4",
      is_rare: "1",
      is_influenced: "0",
      is_fossil: "0",
      is_ess: "0",
      is_craftable: "0",
      is_notable: "0",
      is_catalyst: "0",
      has_items: "1",
      max_sockets: "0",
    },
    {
      id_bgroup: "15",
      name_bgroup: "Invitations",
      max_affix: "6",
      is_rare: "1",
      is_influenced: "0",
      is_fossil: "1",
      is_ess: "0",
      is_craftable: "0",
      is_notable: "0",
      is_catalyst: "0",
      has_items: "0",
      max_sockets: "0",
    },
    {
      id_bgroup: "1",
      name_bgroup: "Jewellery",
      max_affix: "6",
      is_rare: "1",
      is_influenced: "1",
      is_fossil: "1",
      is_ess: "1",
      is_craftable: "1",
      is_notable: "0",
      is_catalyst: "1",
      has_items: "1",
      max_sockets: "0",
    },
    {
      id_bgroup: "9",
      name_bgroup: "Jewels",
      max_affix: "4",
      is_rare: "1",
      is_influenced: "0",
      is_fossil: "1",
      is_ess: "0",
      is_craftable: "0",
      is_notable: "0",
      is_catalyst: "0",
      has_items: "0",
      max_sockets: "0",
    },
    {
      id_bgroup: "11",
      name_bgroup: "Maps",
      max_affix: "6",
      is_rare: "1",
      is_influenced: "0",
      is_fossil: "1",
      is_ess: "0",
      is_craftable: "0",
      is_notable: "0",
      is_catalyst: "0",
      has_items: "0",
      max_sockets: "0",
    },
    {
      id_bgroup: "8",
      name_bgroup: "Offhands",
      max_affix: "6",
      is_rare: "1",
      is_influenced: "1",
      is_fossil: "1",
      is_ess: "1",
      is_craftable: "1",
      is_notable: "0",
      is_catalyst: "0",
      has_items: "1",
      max_sockets: "0",
    },
    {
      id_bgroup: "6",
      name_bgroup: "One-Handed Weapons",
      max_affix: "6",
      is_rare: "1",
      is_influenced: "1",
      is_fossil: "1",
      is_ess: "1",
      is_craftable: "1",
      is_notable: "0",
      is_catalyst: "0",
      has_items: "1",
      max_sockets: "0",
    },
    {
      id_bgroup: "18",
      name_bgroup: "Tinctures",
      max_affix: "2",
      is_rare: "0",
      is_influenced: "0",
      is_fossil: "0",
      is_ess: "0",
      is_craftable: "0",
      is_notable: "0",
      is_catalyst: "0",
      has_items: "1",
      max_sockets: "0",
    },
    {
      id_bgroup: "7",
      name_bgroup: "Two-Handed Weapons",
      max_affix: "6",
      is_rare: "1",
      is_influenced: "1",
      is_fossil: "1",
      is_ess: "1",
      is_craftable: "1",
      is_notable: "0",
      is_catalyst: "0",
      has_items: "1",
      max_sockets: "0",
    },
  ],
  ind: {
    "1": 10,
    "2": 0,
    "3": 1,
    "4": 7,
    "5": 5,
    "6": 14,
    "7": 16,
    "8": 13,
    "9": 11,
    "10": 4,
    "11": 12,
    "12": 2,
    "13": 6,
    "15": 9,
    "18": 15,
    "19": 3,
    "20": 8,
  },
};

export const BASE_ITEM = {
  seq: [
    {
      id_bgroup: "20",
      id_base: "217",
      name_base: "(1) Minor",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "20",
      id_base: "218",
      name_base: "(2) Kamasan / Noble",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "20",
      id_base: "219",
      name_base: "(3) Burial / Totemic",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "20",
      id_base: "220",
      name_base: "(4) Conqueror",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "1",
      id_base: "2",
      name_base: "Amulet",
      is_jewellery: "1",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "17",
      id_base: "210",
      name_base: "Apex Sentinel",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "153",
      name_base: "Area Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant: "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: 10% increased Area Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "128",
      name_base: "Armour",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "70",
      unique_notable: "1",
      enchant: "Adds 2-3 Passive Skills\nAdded Small Passive Skills grant: 15% increased Armour",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "169",
      name_base: "Attack Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "69",
      unique_notable: "0",
      enchant: "Adds 8-12 Passive Skills\nAdded Small Passive Skills grant: 10% increased Attack Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "167",
      name_base: "Attack Damage while Dual Wielding",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "69",
      unique_notable: "0",
      enchant:
        "Adds 8-12 Passive Skills\nAdded Small Passive Skills grant: 12% increased Attack Damage while Dual Wielding",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "168",
      name_base: "Attack Damage while holding a Shield",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "69",
      unique_notable: "0",
      enchant:
        "Adds 8-12 Passive Skills\nAdded Small Passive Skills grant: 12% increased Attack Damage while holding a Shield",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "146",
      name_base: "Aura Effect",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant:
        "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: 6% increased effect of Non-Curse Auras from your Skills",
      is_legacy: "1",
    },
    {
      id_bgroup: "12",
      id_base: "161",
      name_base: "Axe and Sword Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "69",
      unique_notable: "0",
      enchant:
        "Adds 8-12 Passive Skills\nAdded Small Passive Skills grant: Axe Attacks deal 12% increased Damage with Hits and Ailments\nAdded Small Passive Skills grant: Sword Attacks deal 12% increased Damage with Hits and Ailments",
      is_legacy: "0",
    },
    {
      id_bgroup: "1",
      id_base: "3",
      name_base: "Belt",
      is_jewellery: "1",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "181",
      name_base: "Blueprint",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "2",
      id_base: "46",
      name_base: "Body Armour (DEX)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "2",
      id_base: "50",
      name_base: "Body Armour (DEX/INT)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "2",
      id_base: "47",
      name_base: "Body Armour (INT)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "2",
      id_base: "45",
      name_base: "Body Armour (STR)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "2",
      id_base: "48",
      name_base: "Body Armour (STR/DEX)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "2",
      id_base: "51",
      name_base: "Body Armour (STR/DEX/INT)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "2",
      id_base: "49",
      name_base: "Body Armour (STR/INT)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "1",
      id_base: "211",
      name_base: "Bone Ring",
      is_jewellery: "1",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "8",
      id_base: "212",
      name_base: "Bone Spirit Shield",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "3",
      id_base: "40",
      name_base: "Boots (DEX)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "3",
      id_base: "44",
      name_base: "Boots (DEX/INT)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "3",
      id_base: "41",
      name_base: "Boots (INT)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "3",
      id_base: "39",
      name_base: "Boots (STR)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "3",
      id_base: "42",
      name_base: "Boots (STR/DEX)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "3",
      id_base: "43",
      name_base: "Boots (STR/INT)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "3",
      id_base: "201",
      name_base: "Boots (Ward)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "7",
      id_base: "20",
      name_base: "Bow",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "164",
      name_base: "Bow Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "69",
      unique_notable: "0",
      enchant:
        "Adds 8-12 Passive Skills\nAdded Small Passive Skills grant: 12% increased Damage with Bows\nAdded Small Passive Skills grant: 12% increased Damage Over Time with Bow Skills",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "157",
      name_base: "Brand Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant: "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: 12% increased Brand Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "180",
      name_base: "Brooch",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "140",
      name_base: "Burning Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant: "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: 12% increased Burning Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "196",
      name_base: "Burst Band",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "193",
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "130",
      name_base: "Chance to Block Attack Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "70",
      unique_notable: "1",
      enchant: "Adds 2-3 Passive Skills\nAdded Small Passive Skills grant: +1% Chance to Block Attack Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "131",
      name_base: "Chance to Block Spell Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "70",
      unique_notable: "1",
      enchant: "Adds 2-3 Passive Skills\nAdded Small Passive Skills grant: 1% Chance to Block Spell Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "136",
      name_base: "Chance to Suppress Spell Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "70",
      unique_notable: "1",
      enchant: "Adds 2-3 Passive Skills\nAdded Small Passive Skills grant: +2% chance to Suppress Spell Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "158",
      name_base: "Channelling Skill Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant:
        "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: Channelling Skills deal 12% increased Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "176",
      name_base: "Chaos Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "69",
      unique_notable: "0",
      enchant: "Adds 8-12 Passive Skills\nAdded Small Passive Skills grant: 12% increased Chaos Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "141",
      name_base: "Chaos Damage over Time",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant: "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: 12% increased Chaos Damage over Time",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "135",
      name_base: "Chaos Resistance",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "70",
      unique_notable: "1",
      enchant: "Adds 2-3 Passive Skills\nAdded Small Passive Skills grant: +12% to Chaos Resistance",
      is_legacy: "0",
    },
    {
      id_bgroup: "14",
      id_base: "199",
      name_base: "Chromium Watchstone",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "6",
      id_base: "11",
      name_base: "Claw",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "179",
      name_base: "Cloak",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "9",
      id_base: "28",
      name_base: "Cobalt Jewel",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "175",
      name_base: "Cold Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "69",
      unique_notable: "0",
      enchant: "Adds 8-12 Passive Skills\nAdded Small Passive Skills grant: 12% increased Cold Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "143",
      name_base: "Cold Damage over Time",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant: "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: 12% increased Cold Damage over Time",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "133",
      name_base: "Cold Resistance",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "70",
      unique_notable: "1",
      enchant: "Adds 2-3 Passive Skills\nAdded Small Passive Skills grant: +15% to Cold Resistance",
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "182",
      name_base: "Contract",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "6",
      id_base: "67",
      name_base: "Convoking Wand",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "9",
      id_base: "26",
      name_base: "Crimson Jewel",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "151",
      name_base: "Critical Chance",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant: "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: 15% increased Critical Strike Chance",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "147",
      name_base: "Curse Effect",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant: "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: 5% increased Effect of your Curses",
      is_legacy: "1",
    },
    {
      id_bgroup: "12",
      id_base: "205",
      name_base: "Curse Effect",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "70",
      unique_notable: "1",
      enchant: "Adds 2-3 Passive Skills\nAdded Small Passive Skills grant: 3% increased Effect of your Curses",
      is_legacy: "0",
    },
    {
      id_bgroup: "6",
      id_base: "12",
      name_base: "Dagger",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "163",
      name_base: "Dagger and Claw Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "69",
      unique_notable: "0",
      enchant:
        "Adds 8-12 Passive Skills\nAdded Small Passive Skills grant: Dagger Attacks deal 12% increased Damage with Hits and Ailments\nAdded Small Passive Skills grant: Claw Attacks deal 12% increased Damage with Hits and Ailments",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "144",
      name_base: "Damage over Time",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant: "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: 10% increased Damage over Time",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "148",
      name_base: "Damage while you have a Herald",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant:
        "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: 10% increased Damage while affected by a Herald",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "166",
      name_base: "Damage with Two Handed Melee Weapons",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "69",
      unique_notable: "0",
      enchant:
        "Adds 8-12 Passive Skills\nAdded Small Passive Skills grant: 12% increased Damage with Two Handed Weapons",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "145",
      name_base: "Effect of Non-Damaging Ailments",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant:
        "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: 10% increased Effect of Non-Damaging Ailments",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "171",
      name_base: "Elemental Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "69",
      unique_notable: "0",
      enchant: "Adds 8-12 Passive Skills\nAdded Small Passive Skills grant: 10% increased Elemental Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "126",
      name_base: "Energy Shield",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "70",
      unique_notable: "1",
      enchant: "Adds 2-3 Passive Skills\nAdded Small Passive Skills grant: 6% increased maximum Energy Shield",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "129",
      name_base: "Evasion",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "70",
      unique_notable: "1",
      enchant: "Adds 2-3 Passive Skills\nAdded Small Passive Skills grant: 15% increased Evasion Rating",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "150",
      name_base: "Exerted Effect",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant: "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: Exerted Attacks deal 20% increased Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "173",
      name_base: "Fire Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "69",
      unique_notable: "0",
      enchant: "Adds 8-12 Passive Skills\nAdded Small Passive Skills grant: 12% increased Fire Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "132",
      name_base: "Fire Resistance",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "70",
      unique_notable: "1",
      enchant: "Adds 2-3 Passive Skills\nAdded Small Passive Skills grant: +15% to Fire Resistance",
      is_legacy: "0",
    },
    {
      id_bgroup: "19",
      id_base: "216",
      name_base: "Fishing Rod",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "159",
      name_base: "Flask Duration",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant: "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: 6% increased Flask Effect Duration",
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "193",
      name_base: "Gear",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "1",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "9",
      id_base: "32",
      name_base: "Ghastly Eye Jewel",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "5",
      id_base: "34",
      name_base: "Gloves (DEX)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "5",
      id_base: "38",
      name_base: "Gloves (DEX/INT)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "5",
      id_base: "35",
      name_base: "Gloves (INT)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "5",
      id_base: "33",
      name_base: "Gloves (STR)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "5",
      id_base: "36",
      name_base: "Gloves (STR/DEX)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "5",
      id_base: "37",
      name_base: "Gloves (STR/INT)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "5",
      id_base: "202",
      name_base: "Gloves (Ward)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "189",
      name_base: "Grandmaster Keyring",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "183",
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "4",
      id_base: "53",
      name_base: "Helmet (DEX)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "4",
      id_base: "57",
      name_base: "Helmet (DEX/INT)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "4",
      id_base: "54",
      name_base: "Helmet (INT)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "4",
      id_base: "52",
      name_base: "Helmet (STR)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "4",
      id_base: "55",
      name_base: "Helmet (STR/DEX)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "4",
      id_base: "56",
      name_base: "Helmet (STR/INT)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "4",
      id_base: "203",
      name_base: "Helmet (Ward)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "10",
      id_base: "59",
      name_base: "Hybrid Flask",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "9",
      id_base: "31",
      name_base: "Hypnotic Eye Jewel",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "10",
      id_base: "206",
      name_base: "Iron Flask",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "69",
      name_base: "Large Cluster Jewel",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "1",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "125",
      name_base: "Life",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "70",
      unique_notable: "1",
      enchant: "Adds 2-3 Passive Skills\nAdded Small Passive Skills grant: 4% increased maximum Life",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "160",
      name_base: "Life and Mana recovery from Flasks",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant:
        "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: 10% increased Life Recovery from Flasks\nAdded Small Passive Skills grant: 10% increased Mana Recovery from Flasks",
      is_legacy: "0",
    },
    {
      id_bgroup: "10",
      id_base: "60",
      name_base: "Life Flask",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "174",
      name_base: "Lightning Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "69",
      unique_notable: "0",
      enchant: "Adds 8-12 Passive Skills\nAdded Small Passive Skills grant: 12% increased Lightning Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "134",
      name_base: "Lightning Resistance",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "70",
      unique_notable: "1",
      enchant: "Adds 2-3 Passive Skills\nAdded Small Passive Skills grant: +15% to Lightning Resistance",
      is_legacy: "0",
    },
    {
      id_bgroup: "11",
      id_base: "64",
      name_base: "Low Tier (1-5)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "162",
      name_base: "Mace and Staff Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "69",
      unique_notable: "0",
      enchant:
        "Adds 8-12 Passive Skills\nAdded Small Passive Skills grant: Mace or Sceptre Attacks deal 12% increased Damage with Hits and Ailments\nAdded Small Passive Skills grant: Staff Attacks deal 12% increased Damage with Hits and Ailments",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "127",
      name_base: "Mana",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "70",
      unique_notable: "1",
      enchant: "Adds 2-3 Passive Skills\nAdded Small Passive Skills grant: 6% increased maximum Mana",
      is_legacy: "0",
    },
    {
      id_bgroup: "10",
      id_base: "61",
      name_base: "Mana Flask",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "204",
      name_base: "Mana Reservation",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "70",
      unique_notable: "1",
      enchant:
        "Adds 2-3 Passive Skills\nAdded Small Passive Skills grant: 6% increased Mana Reservation Efficiency of Skills",
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "184",
      name_base: "Master Lockpick",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "183",
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "15",
      id_base: "207",
      name_base: "Maven's Invitation",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "71",
      name_base: "Medium Cluster Jewel",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "1",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "11",
      id_base: "65",
      name_base: "Mid Tier (6-10)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "177",
      name_base: "Minion Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "69",
      unique_notable: "0",
      enchant: "Adds 8-12 Passive Skills\nAdded Small Passive Skills grant: Minions deal 10% increased Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "149",
      name_base: "Minion Damage while you have a Herald",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant:
        "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: Minions deal 10% increased Damage while you are affected by a Herald",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "152",
      name_base: "Minion Life",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant: "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: Minions have 12% increased maximum Life",
      is_legacy: "0",
    },
    {
      id_bgroup: "9",
      id_base: "29",
      name_base: "Murderous Eye Jewel",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "194",
      name_base: "Obsidian Sharpening Stone",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "193",
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "6",
      id_base: "15",
      name_base: "One Hand Axe",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "6",
      id_base: "16",
      name_base: "One Hand Mace",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "6",
      id_base: "13",
      name_base: "One Hand Sword",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "17",
      id_base: "209",
      name_base: "Pandemonium Sentinel",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "172",
      name_base: "Physical Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "69",
      unique_notable: "0",
      enchant: "Adds 8-12 Passive Skills\nAdded Small Passive Skills grant: 12% increased Physical Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "142",
      name_base: "Physical Damage over Time",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant: "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: 12% increased Physical Damage over Time",
      is_legacy: "0",
    },
    {
      id_bgroup: "14",
      id_base: "197",
      name_base: "Platinum Watchstone",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "195",
      name_base: "Precise Arrowhead",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "193",
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "9",
      id_base: "68",
      name_base: "Prismatic Jewel",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "154",
      name_base: "Projectile Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant: "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: 10% increased Projectile Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "8",
      id_base: "4",
      name_base: "Quiver",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "192",
      name_base: "Regicide Disguise Kit",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "183",
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "1",
      id_base: "1",
      name_base: "Ring",
      is_jewellery: "1",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "6",
      id_base: "19",
      name_base: "Rune Dagger",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "6",
      id_base: "17",
      name_base: "Sceptre",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "9",
      id_base: "30",
      name_base: "Searching Eye Jewel",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "8",
      id_base: "6",
      name_base: "Shield (DEX)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "8",
      id_base: "10",
      name_base: "Shield (DEX/INT)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "8",
      id_base: "7",
      name_base: "Shield (INT)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "8",
      id_base: "5",
      name_base: "Shield (STR)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "8",
      id_base: "8",
      name_base: "Shield (STR/DEX)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "8",
      id_base: "9",
      name_base: "Shield (STR/INT)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "190",
      name_base: "Silkweave Sole",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "183",
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "10",
      id_base: "63",
      name_base: "Silver Flask",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "70",
      name_base: "Small Cluster Jewel",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "1",
      master_base: null,
      unique_notable: "1",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "170",
      name_base: "Spell Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "69",
      unique_notable: "0",
      enchant: "Adds 8-12 Passive Skills\nAdded Small Passive Skills grant: 10% increased Spell Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "7",
      id_base: "21",
      name_base: "Staff",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "17",
      id_base: "208",
      name_base: "Stalker Sentinel",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "185",
      name_base: "Steel Bracers",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "183",
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "186",
      name_base: "Thaumaturgical Sensing Charm",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "183",
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "188",
      name_base: "Thaumaturgical Ward",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "183",
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "191",
      name_base: "Thaumetic Blowtorch",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "183",
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "187",
      name_base: "Thaumetic Flashpowder",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "183",
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "6",
      id_base: "14",
      name_base: "Thrusting One Hand Sword",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "9",
      id_base: "200",
      name_base: "Timeless Jewel",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "18",
      id_base: "215",
      name_base: "Tincture",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "14",
      id_base: "198",
      name_base: "Titanium Watchstone",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "183",
      name_base: "Tools",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "1",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "11",
      id_base: "66",
      name_base: "Top Tier (11-16)",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "156",
      name_base: "Totem Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant: "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: 12% increased Totem Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "155",
      name_base: "Trap and Mine Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "71",
      unique_notable: "0",
      enchant:
        "Adds 4-6 Passive Skills\nAdded Small Passive Skills grant: 12% increased Trap Damage\nAdded Small Passive Skills grant: 12% increased Mine Damage",
      is_legacy: "0",
    },
    {
      id_bgroup: "13",
      id_base: "178",
      name_base: "Trinket",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "7",
      id_base: "24",
      name_base: "Two Hand Axe",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "7",
      id_base: "23",
      name_base: "Two Hand Mace",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "7",
      id_base: "22",
      name_base: "Two Hand Sword",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "11",
      id_base: "214",
      name_base: "Uber Tier",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "1",
      id_base: "58",
      name_base: "Unset Ring",
      is_jewellery: "1",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "10",
      id_base: "62",
      name_base: "Utility Flask",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "9",
      id_base: "27",
      name_base: "Viridian Jewel",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "6",
      id_base: "18",
      name_base: "Wand",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
    {
      id_bgroup: "12",
      id_base: "165",
      name_base: "Wand Damage",
      is_jewellery: "0",
      base_type: "child",
      has_childs: "0",
      master_base: "69",
      unique_notable: "0",
      enchant:
        "Adds 8-12 Passive Skills\nAdded Small Passive Skills grant: Wand Attacks deal 12% increased Damage with Hits and Ailments",
      is_legacy: "0",
    },
    {
      id_bgroup: "7",
      id_base: "25",
      name_base: "Warstaff",
      is_jewellery: "0",
      base_type: "master",
      has_childs: "0",
      master_base: null,
      unique_notable: "0",
      enchant: null,
      is_legacy: "0",
    },
  ],
  ind: {
    "1": 123,
    "2": 4,
    "3": 13,
    "4": 121,
    "5": 130,
    "6": 127,
    "7": 129,
    "8": 131,
    "9": 132,
    "10": 128,
    "11": 45,
    "12": 57,
    "13": 113,
    "14": 144,
    "15": 111,
    "16": 112,
    "17": 125,
    "18": 160,
    "19": 124,
    "20": 31,
    "21": 137,
    "22": 155,
    "23": 154,
    "24": 153,
    "25": 162,
    "26": 53,
    "27": 159,
    "28": 47,
    "29": 109,
    "30": 126,
    "31": 89,
    "32": 72,
    "33": 76,
    "34": 73,
    "35": 75,
    "36": 77,
    "37": 78,
    "38": 74,
    "39": 27,
    "40": 24,
    "41": 26,
    "42": 28,
    "43": 29,
    "44": 25,
    "45": 18,
    "46": 15,
    "47": 17,
    "48": 19,
    "49": 21,
    "50": 16,
    "51": 20,
    "52": 84,
    "53": 81,
    "54": 83,
    "55": 85,
    "56": 86,
    "57": 82,
    "58": 157,
    "59": 88,
    "60": 94,
    "61": 100,
    "62": 158,
    "63": 134,
    "64": 97,
    "65": 105,
    "66": 149,
    "67": 52,
    "68": 119,
    "69": 91,
    "70": 135,
    "71": 104,
    "125": 92,
    "126": 64,
    "127": 99,
    "128": 7,
    "129": 65,
    "130": 37,
    "131": 38,
    "132": 68,
    "133": 50,
    "134": 96,
    "135": 43,
    "136": 39,
    "140": 35,
    "141": 42,
    "142": 116,
    "143": 49,
    "144": 59,
    "145": 62,
    "146": 11,
    "147": 55,
    "148": 60,
    "149": 107,
    "150": 66,
    "151": 54,
    "152": 108,
    "153": 6,
    "154": 120,
    "155": 151,
    "156": 150,
    "157": 33,
    "158": 40,
    "159": 70,
    "160": 93,
    "161": 12,
    "162": 98,
    "163": 58,
    "164": 32,
    "165": 161,
    "166": 61,
    "167": 9,
    "168": 10,
    "169": 8,
    "170": 136,
    "171": 63,
    "172": 115,
    "173": 67,
    "174": 95,
    "175": 48,
    "176": 41,
    "177": 106,
    "178": 152,
    "179": 46,
    "180": 34,
    "181": 14,
    "182": 51,
    "183": 148,
    "184": 102,
    "185": 139,
    "186": 140,
    "187": 143,
    "188": 141,
    "189": 80,
    "190": 133,
    "191": 142,
    "192": 122,
    "193": 71,
    "194": 110,
    "195": 118,
    "196": 36,
    "197": 117,
    "198": 147,
    "199": 44,
    "200": 145,
    "201": 30,
    "202": 79,
    "203": 87,
    "204": 101,
    "205": 56,
    "206": 90,
    "207": 103,
    "208": 138,
    "209": 114,
    "210": 5,
    "211": 22,
    "212": 23,
    "214": 156,
    "215": 146,
    "216": 69,
    "217": 0,
    "218": 1,
    "219": 2,
    "220": 3,
  },
  items: {
    "1": [
      0, 16, 26, 48, 61, 90, 125, 131, 153, 197, 206, 207, 208, 244, 245, 248, 249, 251, 254, 256, 259, 303, 397, 782,
      878, 884, 891, 895, 900, 962, 963, 964, 966, 986, 987,
    ],
    "2": [9, 30, 37, 76, 79, 80, 144, 185, 190, 205, 252, 487, 543, 857, 858, 866, 985, 988, 989],
    "3": [22, 23, 28, 104, 105, 126, 191, 203, 818, 844, 856, 965, 979],
    "4": [55, 92, 139, 196, 253, 308, 385, 430, 473, 516, 603, 684, 758, 990, 991],
    "5": [21, 59, 116, 159, 238, 304, 361, 409, 455, 500, 550, 592, 641, 682, 721, 761, 820, 933, 954, 976],
    "6": [25, 89, 152, 231, 295, 341, 403, 446, 492, 531, 580, 622, 670, 715, 749, 797, 931, 956, 974],
    "7": [42, 101, 233, 286, 329, 394, 471, 517, 575, 612, 707, 736, 790, 932, 961, 983],
    "8": [62, 123, 204, 277, 336, 413, 485, 521, 577, 643, 702, 747, 809],
    "9": [81, 134, 202, 274, 339, 422, 496, 538, 588, 646, 689, 740, 771],
    "10": [66, 122, 186, 268, 332, 414, 476, 523, 584, 629, 693, 757, 827],
    "11": [
      36, 82, 118, 158, 217, 263, 306, 340, 370, 393, 424, 457, 494, 524, 561, 595, 628, 635, 678, 694, 720, 759, 776,
      828, 840, 943, 955, 984,
    ],
    "12": [7, 65, 149, 301, 374, 440, 555, 610, 660, 822, 938, 958, 980],
    "13": [
      8, 17, 24, 58, 109, 142, 211, 235, 279, 316, 342, 366, 400, 432, 460, 501, 536, 576, 597, 608, 632, 668, 697, 729,
      752, 780, 830, 934, 946, 969,
    ],
    "14": [
      40, 83, 120, 156, 222, 261, 300, 347, 380, 396, 419, 453, 495, 525, 557, 589, 618, 633, 677, 700, 727, 760, 777,
      816, 839,
    ],
    "15": [
      27, 71, 114, 151, 212, 247, 294, 335, 352, 373, 415, 451, 489, 508, 548, 585, 607, 623, 657, 686, 710, 743, 767,
      798, 837, 939, 950, 981,
    ],
    "16": [
      2, 67, 111, 150, 210, 236, 278, 315, 348, 362, 398, 441, 459, 502, 540, 574, 594, 604, 644, 667, 696, 723, 746,
      783, 807, 935, 948, 973,
    ],
    "17": [
      3, 60, 102, 147, 199, 241, 289, 323, 357, 372, 406, 435, 463, 499, 541, 564, 601, 611, 645, 672, 701, 730, 748,
      793, 824, 940, 960, 968,
    ],
    "18": [4, 70, 121, 177, 246, 305, 345, 353, 421, 478, 518, 573, 598, 606, 653, 699, 742, 786, 821, 928, 947, 967],
    "19": [103, 188, 237, 293, 320, 399, 461, 503, 542, 569, 642, 692, 724, 755, 773, 936, 951, 978],
    "20": [
      1, 64, 95, 138, 178, 227, 290, 314, 358, 375, 401, 434, 467, 504, 537, 567, 617, 627, 631, 673, 687, 726, 754,
      775, 836, 937, 952, 982,
    ],
    "21": [50, 97, 173, 291, 368, 395, 483, 558, 626, 640, 695, 756, 808, 944, 959, 972],
    "22": [
      31, 88, 119, 166, 219, 275, 326, 351, 367, 423, 462, 510, 554, 586, 613, 621, 655, 683, 717, 738, 764, 810, 942,
      945, 971,
    ],
    "23": [
      32, 91, 129, 164, 223, 266, 317, 343, 383, 425, 468, 514, 552, 579, 616, 624, 647, 685, 712, 737, 770, 794, 929,
      949, 977,
    ],
    "24": [
      56, 94, 137, 175, 230, 285, 334, 369, 390, 444, 481, 522, 560, 587, 636, 659, 676, 691, 728, 751, 792, 812, 941,
      953, 970,
    ],
    "25": [133, 229, 337, 439, 527, 596, 666, 722, 778, 930, 957, 975],
    "26": [194],
    "27": [209],
    "28": [193],
    "29": [14],
    "30": [18],
    "31": [10],
    "32": [6],
    "33": [11, 108, 115, 228, 363, 408, 426, 498, 570, 716, 804, 826, 829, 887, 908],
    "34": [39, 93, 112, 214, 331, 402, 417, 484, 583, 704, 815, 825, 831, 875, 923],
    "35": [44, 106, 132, 257, 371, 416, 442, 507, 591, 661, 803, 811, 819, 889, 925],
    "36": [49, 146, 267, 382, 456, 530, 652, 763, 870, 927],
    "37": [77, 184, 321, 391, 458, 553, 625, 750, 806, 882, 914],
    "38": [68, 155, 309, 384, 470, 532, 630, 765, 877, 916],
    "39": [12, 98, 187, 232, 333, 386, 491, 535, 581, 705, 789, 888, 894, 909],
    "40": [38, 124, 192, 218, 344, 410, 465, 547, 600, 703, 802, 874, 899, 922],
    "41": [45, 100, 195, 225, 322, 405, 464, 539, 565, 680, 769, 890, 896, 924],
    "42": [74, 171, 297, 381, 450, 556, 651, 732, 833, 869, 926],
    "43": [57, 135, 288, 376, 431, 528, 637, 718, 834, 881, 913],
    "44": [75, 154, 269, 346, 445, 497, 590, 709, 799, 813, 832, 876, 915],
    "45": [15, 69, 160, 216, 282, 311, 360, 388, 433, 486, 519, 572, 609, 648, 688, 735, 774, 855, 879, 917],
    "46": [29, 99, 157, 260, 281, 327, 365, 389, 436, 480, 520, 566, 615, 649, 690, 745, 772, 854, 868, 919],
    "47": [41, 117, 182, 258, 287, 324, 350, 392, 443, 477, 529, 568, 614, 654, 698, 744, 791, 842, 883, 921],
    "48": [53, 87, 163, 215, 284, 325, 354, 407, 449, 493, 533, 578, 619, 662, 711, 753, 805, 847, 880, 904],
    "49": [47, 85, 162, 213, 283, 319, 359, 411, 452, 506, 549, 593, 638, 681, 719, 768, 823, 849, 886, 918],
    "50": [51, 96, 174, 224, 292, 328, 349, 428, 466, 509, 559, 605, 656, 708, 731, 788, 835, 853, 893, 912],
    "51": [198, 814, 841],
    "52": [13, 78, 168, 262, 355, 429, 513, 599, 665, 741, 795, 848, 871, 906],
    "53": [33, 113, 200, 307, 437, 505, 602, 674, 725, 817, 845, 873, 911],
    "54": [43, 86, 165, 264, 338, 412, 515, 582, 658, 739, 796, 852, 892, 910],
    "55": [46, 136, 148, 234, 330, 379, 454, 472, 551, 634, 713, 766, 851, 863, 872, 907],
    "56": [63, 130, 145, 221, 310, 387, 469, 479, 571, 639, 714, 785, 843, 846, 859, 885, 905],
    "57": [54, 107, 143, 161, 280, 356, 404, 475, 490, 562, 620, 706, 762, 850, 860, 867, 920],
    "58": [488],
    "59": [110, 201, 302, 420, 544, 669],
    "60": [19, 34, 72, 127, 169, 239, 298, 377, 447, 545, 663, 733],
    "61": [20, 35, 73, 128, 170, 240, 299, 378, 448, 546, 664, 734],
    "62": [52, 84, 140, 167, 180, 181, 183, 220, 265, 270, 271, 272, 273, 276, 364, 418],
    "63": [226],
    "67": [189, 534, 838],
    "179": [679, 864, 898, 903],
    "180": [675, 862, 897, 902],
    "201": [243, 512, 801],
    "202": [242, 511, 800],
    "203": [255, 526, 787],
    "206": [427],
    "211": [250, 296],
    "212": [141, 438, 650],
    "215": [172, 176, 179, 312, 313, 318, 474, 482, 563, 671],
    "216": [5],
    "217": [781],
    "218": [779, 784],
    "219": [861, 865],
    "220": [901],
  },
};
