export const INFLUENCE = {
  seq: [
    {
      is_influence: "0",
      id_mgroup: "1",
      name_mgroup: "Base",
      poedb_id: null,
      paste_link: null,
      is_main: "1",
      max_chosen: "6",
      is_compute: "1",
    },
    {
      is_influence: "1",
      id_mgroup: "4",
      name_mgroup: "Crusader",
      poedb_id: "crusader",
      paste_link: "Crusader Item",
      is_main: "0",
      max_chosen: "0",
      is_compute: "1",
    },
    {
      is_influence: "1",
      id_mgroup: "3",
      name_mgroup: "Elder",
      poedb_id: "elder",
      paste_link: "Elder Item",
      is_main: "0",
      max_chosen: "0",
      is_compute: "1",
    },
    {
      is_influence: "1",
      id_mgroup: "5",
      name_mgroup: "Hunter",
      poedb_id: "basilisk",
      paste_link: "Hunter Item",
      is_main: "0",
      max_chosen: "0",
      is_compute: "1",
    },
    {
      is_influence: "1",
      id_mgroup: "7",
      name_mgroup: "Redeemer",
      poedb_id: "eyrie",
      paste_link: "Redeemer Item",
      is_main: "0",
      max_chosen: "0",
      is_compute: "1",
    },
    {
      is_influence: "1",
      id_mgroup: "2",
      name_mgroup: "Shaper",
      poedb_id: "shaper",
      paste_link: "Shaper Item",
      is_main: "0",
      max_chosen: "0",
      is_compute: "1",
    },
    {
      is_influence: "1",
      id_mgroup: "6",
      name_mgroup: "Warlord",
      poedb_id: "adjudicator",
      paste_link: "Warlord Item",
      is_main: "0",
      max_chosen: "0",
      is_compute: "1",
    },
    {
      is_influence: "0",
      id_mgroup: "8",
      name_mgroup: "Fossil",
      poedb_id: "delve",
      paste_link: null,
      is_main: "0",
      max_chosen: "6",
      is_compute: "1",
    },
    {
      is_influence: "0",
      id_mgroup: "11",
      name_mgroup: "Crafted",
      poedb_id: null,
      paste_link: null,
      is_main: "0",
      max_chosen: "1",
      is_compute: "0",
    },
    {
      is_influence: "0",
      id_mgroup: "12",
      name_mgroup: "Delve",
      poedb_id: null,
      paste_link: null,
      is_main: "0",
      max_chosen: "1",
      is_compute: "0",
    },
    {
      is_influence: "0",
      id_mgroup: "13",
      name_mgroup: "Essence",
      poedb_id: null,
      paste_link: null,
      is_main: "0",
      max_chosen: "1",
      is_compute: "0",
    },
    {
      is_influence: "0",
      id_mgroup: "16",
      name_mgroup: "Haunted",
      poedb_id: null,
      paste_link: null,
      is_main: "0",
      max_chosen: "0",
      is_compute: "0",
    },
    {
      is_influence: "0",
      id_mgroup: "9",
      name_mgroup: "Incursion",
      poedb_id: null,
      paste_link: null,
      is_main: "0",
      max_chosen: "1",
      is_compute: "0",
    },
    {
      is_influence: "0",
      id_mgroup: "14",
      name_mgroup: "Other",
      poedb_id: null,
      paste_link: null,
      is_main: "0",
      max_chosen: "0",
      is_compute: "0",
    },
    {
      is_influence: "0",
      id_mgroup: "15",
      name_mgroup: "Sentinel",
      poedb_id: null,
      paste_link: null,
      is_main: "0",
      max_chosen: "0",
      is_compute: "0",
    },
    {
      is_influence: "0",
      id_mgroup: "999",
      name_mgroup: "Special",
      poedb_id: null,
      paste_link: null,
      is_main: "0",
      max_chosen: "0",
      is_compute: "0",
    },
    {
      is_influence: "0",
      id_mgroup: "10",
      name_mgroup: "Veiled",
      poedb_id: null,
      paste_link: null,
      is_main: "0",
      max_chosen: "1",
      is_compute: "0",
    },
  ],
  ind: {
    "1": 0,
    "2": 5,
    "3": 2,
    "4": 1,
    "5": 3,
    "6": 6,
    "7": 4,
    "8": 7,
    "9": 12,
    "10": 16,
    "11": 8,
    "12": 9,
    "13": 10,
    "14": 13,
    "15": 14,
    "16": 11,
    "999": 15,
  },
};
