export const TYPES = {
  seq: [
    {
      id_mtype: "30",
      poedb_id: "ailment",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "1",
      parent_id: null,
      name_mtype: "Ailment",
    },
    {
      id_mtype: "24",
      poedb_id: "armour",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "0",
      parent_id: "4",
      name_mtype: "Armor",
    },
    {
      id_mtype: "3",
      poedb_id: "attack",
      jewellery_tag: "0",
      harvest: "1",
      tangled: "1",
      parent_id: null,
      name_mtype: "Attack",
    },
    {
      id_mtype: "31",
      poedb_id: "attribute",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "1",
      parent_id: null,
      name_mtype: "Attribute",
    },
    {
      id_mtype: "23",
      poedb_id: "aura",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "1",
      parent_id: null,
      name_mtype: "Aura",
    },
    {
      id_mtype: "19",
      poedb_id: "bleed",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "0",
      parent_id: null,
      name_mtype: "Bleed",
    },
    {
      id_mtype: "13",
      poedb_id: "caster",
      jewellery_tag: "0",
      harvest: "1",
      tangled: "1",
      parent_id: null,
      name_mtype: "Caster",
    },
    {
      id_mtype: "21",
      poedb_id: "jewellery_attack",
      jewellery_tag: "1",
      harvest: "0",
      tangled: "0",
      parent_id: null,
      name_mtype: "Cat. Attack",
    },
    {
      id_mtype: "11",
      poedb_id: "jewellery_attribute",
      jewellery_tag: "1",
      harvest: "0",
      tangled: "0",
      parent_id: null,
      name_mtype: "Cat. Attribute",
    },
    {
      id_mtype: "27",
      poedb_id: "jewellery_caster",
      jewellery_tag: "1",
      harvest: "0",
      tangled: "0",
      parent_id: null,
      name_mtype: "Cat. Caster",
    },
    {
      id_mtype: "22",
      poedb_id: "jewellery_defense",
      jewellery_tag: "1",
      harvest: "0",
      tangled: "0",
      parent_id: null,
      name_mtype: "Cat. Defense",
    },
    {
      id_mtype: "10",
      poedb_id: "jewellery_elemental",
      jewellery_tag: "1",
      harvest: "0",
      tangled: "0",
      parent_id: null,
      name_mtype: "Cat. Elemental",
    },
    {
      id_mtype: "12",
      poedb_id: "jewellery_resistance",
      jewellery_tag: "1",
      harvest: "0",
      tangled: "0",
      parent_id: null,
      name_mtype: "Cat. Resistance",
    },
    {
      id_mtype: "18",
      poedb_id: "jewellery_resource",
      jewellery_tag: "1",
      harvest: "0",
      tangled: "0",
      parent_id: null,
      name_mtype: "Cat. Resource",
    },
    {
      id_mtype: "16",
      poedb_id: "chaos",
      jewellery_tag: "0",
      harvest: "1",
      tangled: "1",
      parent_id: null,
      name_mtype: "Chaos",
    },
    {
      id_mtype: "36",
      poedb_id: "chaos_damage",
      jewellery_tag: "1",
      harvest: "0",
      tangled: "0",
      parent_id: null,
      name_mtype: "Chaos Damage",
    },
    {
      id_mtype: "7",
      poedb_id: "cold",
      jewellery_tag: "0",
      harvest: "1",
      tangled: "1",
      parent_id: "20",
      name_mtype: "Cold",
    },
    {
      id_mtype: "29",
      poedb_id: "critical",
      jewellery_tag: "0",
      harvest: "1",
      tangled: "1",
      parent_id: null,
      name_mtype: "Critical",
    },
    {
      id_mtype: "32",
      poedb_id: "curse",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "1",
      parent_id: null,
      name_mtype: "Curse",
    },
    {
      id_mtype: "33",
      poedb_id: "damage",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "1",
      parent_id: null,
      name_mtype: "Damage",
    },
    {
      id_mtype: "4",
      poedb_id: "defences",
      jewellery_tag: "0",
      harvest: "1",
      tangled: "1",
      parent_id: null,
      name_mtype: "Defences",
    },
    {
      id_mtype: "38",
      poedb_id: "drop",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "0",
      parent_id: null,
      name_mtype: "Drop",
    },
    {
      id_mtype: "20",
      poedb_id: "elemental",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "1",
      parent_id: null,
      name_mtype: "Elemental",
    },
    {
      id_mtype: "25",
      poedb_id: "energy_shield",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "0",
      parent_id: "4",
      name_mtype: "Energy Shield",
    },
    {
      id_mtype: "26",
      poedb_id: "evasion",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "0",
      parent_id: "4",
      name_mtype: "Evasion",
    },
    {
      id_mtype: "6",
      poedb_id: "fire",
      jewellery_tag: "0",
      harvest: "1",
      tangled: "1",
      parent_id: "20",
      name_mtype: "Fire",
    },
    {
      id_mtype: "34",
      poedb_id: "gem",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "1",
      parent_id: null,
      name_mtype: "Gem",
    },
    {
      id_mtype: "9",
      poedb_id: "gem_level",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "0",
      parent_id: null,
      name_mtype: "Gem Level",
    },
    {
      id_mtype: "1",
      poedb_id: "life",
      jewellery_tag: "0",
      harvest: "1",
      tangled: "1",
      parent_id: null,
      name_mtype: "Life",
    },
    {
      id_mtype: "28",
      poedb_id: "flat_life_regen",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "0",
      parent_id: null,
      name_mtype: "Life Regen",
    },
    {
      id_mtype: "8",
      poedb_id: "lightning",
      jewellery_tag: "0",
      harvest: "1",
      tangled: "1",
      parent_id: "20",
      name_mtype: "Lightning",
    },
    {
      id_mtype: "2",
      poedb_id: "mana",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "1",
      parent_id: null,
      name_mtype: "Mana",
    },
    {
      id_mtype: "15",
      poedb_id: "minion",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "1",
      parent_id: null,
      name_mtype: "Minion",
    },
    {
      id_mtype: "5",
      poedb_id: "physical",
      jewellery_tag: "0",
      harvest: "1",
      tangled: "1",
      parent_id: null,
      name_mtype: "Physical",
    },
    {
      id_mtype: "37",
      poedb_id: "physical_damage",
      jewellery_tag: "1",
      harvest: "0",
      tangled: "0",
      parent_id: null,
      name_mtype: "Physical Damage",
    },
    {
      id_mtype: "17",
      poedb_id: "poison",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "0",
      parent_id: null,
      name_mtype: "Poison",
    },
    {
      id_mtype: "35",
      poedb_id: "resistance",
      jewellery_tag: "0",
      harvest: "0",
      tangled: "1",
      parent_id: null,
      name_mtype: "Resistance",
    },
    {
      id_mtype: "14",
      poedb_id: "speed",
      jewellery_tag: "0",
      harvest: "1",
      tangled: "1",
      parent_id: null,
      name_mtype: "Speed",
    },
  ],
  ind: {
    "1": 28,
    "2": 31,
    "3": 2,
    "4": 20,
    "5": 33,
    "6": 25,
    "7": 16,
    "8": 30,
    "9": 27,
    "10": 11,
    "11": 8,
    "12": 12,
    "13": 6,
    "14": 37,
    "15": 32,
    "16": 14,
    "17": 35,
    "18": 13,
    "19": 5,
    "20": 22,
    "21": 7,
    "22": 10,
    "23": 4,
    "24": 1,
    "25": 23,
    "26": 24,
    "27": 9,
    "28": 29,
    "29": 17,
    "30": 0,
    "31": 3,
    "32": 18,
    "33": 19,
    "34": 26,
    "35": 36,
    "36": 15,
    "37": 34,
    "38": 21,
  },
};
