export const sampleItem1 = {
  name: "Heathen Wand",
  quality: "20",
  crit: "8.00",
  aps: "1.45",
  base: ["Shaper"],
  ilevel: 83,
  implicit: ["10% increased Cast Speed"],
  mods: [
    {
      id_modifier: "679",
      modgroup: "WeaponCasterDamagePrefix",
      modgroups: '["WeaponCasterDamagePrefix"]',
      affix: "prefix",
      id_mgroup: "2",
      name_modifier: "Socketed Gems are Supported by Level # Cold Penetration, #% increased Cold Damage",
      id_fossil: null,
      mtypes: "|10|7|33|20|34|",
      meta: null,
      mtags: "caster",
      hybrid: "1",
      notable: "0",
      vex: "0",
      amg: null,
      exkey: null,
      ubt: null,
      hr: false,
      ha: false,
      isCraft: false,
      tag: [
        {
          id_mtype: "7",
          poedb_id: "cold",
          jewellery_tag: "0",
          harvest: "1",
          tangled: "1",
          parent_id: "20",
          name_mtype: "Cold",
        },
        {
          id_mtype: "33",
          poedb_id: "damage",
          jewellery_tag: "0",
          harvest: "0",
          tangled: "1",
          parent_id: null,
          name_mtype: "Damage",
        },
        {
          id_mtype: "20",
          poedb_id: "elemental",
          jewellery_tag: "0",
          harvest: "0",
          tangled: "1",
          parent_id: null,
          name_mtype: "Elemental",
        },
        {
          id_mtype: "34",
          poedb_id: "gem",
          jewellery_tag: "0",
          harvest: "0",
          tangled: "1",
          parent_id: null,
          name_mtype: "Gem",
        },
      ],
    },
    {
      id_modifier: "2369",
      modgroup: "SupportedByAreaProjectile",
      modgroups: '["SupportedByAreaProjectile"]',
      affix: "suffix",
      id_mgroup: "2",
      name_modifier: "Socketed Gems are Supported by Level # Volley, #% increased Projectile Speed",
      id_fossil: null,
      mtypes: "|34|14|",
      meta: null,
      mtags: null,
      hybrid: "1",
      notable: "0",
      vex: "0",
      amg: null,
      exkey: null,
      ubt: null,
      hr: false,
      ha: false,
      isCraft: false,
      tag: [
        {
          id_mtype: "34",
          poedb_id: "gem",
          jewellery_tag: "0",
          harvest: "0",
          tangled: "1",
          parent_id: null,
          name_mtype: "Gem",
        },
        {
          id_mtype: "14",
          poedb_id: "speed",
          jewellery_tag: "0",
          harvest: "1",
          tangled: "1",
          parent_id: null,
          name_mtype: "Speed",
        },
      ],
    },
    {
      id_modifier: "2964",
      modgroup: "ItemGenerationCanHaveMultipleCraftedMods",
      modgroups: '["ItemGenerationCanHaveMultipleCraftedMods"]',
      affix: "suffix",
      id_mgroup: "11",
      name_modifier: "Can have up to 3 Crafted Modifiers",
      id_fossil: null,
      mtypes: "",
      meta: "mul_mods",
      mtags: null,
      hybrid: "0",
      notable: "0",
      vex: "0",
      amg: null,
      exkey: null,
      ubt: null,
      hr: false,
      ha: false,
      isCraft: true,
      tag: [],
    },
    {
      id_modifier: "2837",
      modgroup: "LocalAttackReduceEnemyElementalResistance",
      modgroups: '["LocalAttackReduceEnemyElementalResistance"]',
      affix: "prefix",
      id_mgroup: "11",
      name_modifier: "Attacks with this Weapon Penetrate #% Elemental Resistances",
      id_fossil: null,
      mtypes: "|33|20|3|10|21|",
      meta: null,
      mtags: null,
      hybrid: "0",
      notable: "0",
      vex: "0",
      amg: null,
      exkey: null,
      ubt: null,
      hr: true,
      ha: false,
      isCraft: true,
      tag: [
        {
          id_mtype: "33",
          poedb_id: "damage",
          jewellery_tag: "0",
          harvest: "0",
          tangled: "1",
          parent_id: null,
          name_mtype: "Damage",
        },
        {
          id_mtype: "20",
          poedb_id: "elemental",
          jewellery_tag: "0",
          harvest: "0",
          tangled: "1",
          parent_id: null,
          name_mtype: "Elemental",
        },
        {
          id_mtype: "3",
          poedb_id: "attack",
          jewellery_tag: "0",
          harvest: "1",
          tangled: "1",
          parent_id: null,
          name_mtype: "Attack",
        },
      ],
    },
    {
      id_modifier: "2838",
      modgroup: "ChaosPenetrationWithAttacks",
      modgroups: '["ChaosPenetrationWithAttacks"]',
      affix: "prefix",
      id_mgroup: "11",
      name_modifier: "Attacks with this Weapon Penetrate #% Chaos Resistance",
      id_fossil: null,
      mtypes: "|36|33|16|3|21|",
      meta: null,
      mtags: null,
      hybrid: "0",
      notable: "0",
      vex: "0",
      amg: null,
      exkey: null,
      ubt: null,
      hr: true,
      ha: false,
      isCraft: true,
      tag: [
        {
          id_mtype: "33",
          poedb_id: "damage",
          jewellery_tag: "0",
          harvest: "0",
          tangled: "1",
          parent_id: null,
          name_mtype: "Damage",
        },
        {
          id_mtype: "16",
          poedb_id: "chaos",
          jewellery_tag: "0",
          harvest: "1",
          tangled: "1",
          parent_id: null,
          name_mtype: "Chaos",
        },
        {
          id_mtype: "3",
          poedb_id: "attack",
          jewellery_tag: "0",
          harvest: "1",
          tangled: "1",
          parent_id: null,
          name_mtype: "Attack",
        },
      ],
    },
    {
      id_modifier: "1762",
      modgroup: "IncreasedAttackSpeed",
      modgroups: '["IncreasedAttackSpeed"]',
      affix: "suffix",
      id_mgroup: "2",
      name_modifier: "Socketed Gems are Supported by Level # Faster Casting, #% increased Cast Speed",
      id_fossil: null,
      mtypes: "|13|14|34|27|",
      meta: null,
      mtags: "caster",
      hybrid: "1",
      notable: "0",
      vex: "0",
      amg: null,
      exkey: null,
      ubt: null,
      hr: false,
      ha: false,
      isCraft: false,
      tag: [
        {
          id_mtype: "13",
          poedb_id: "caster",
          jewellery_tag: "0",
          harvest: "1",
          tangled: "1",
          parent_id: null,
          name_mtype: "Caster",
        },
        {
          id_mtype: "14",
          poedb_id: "speed",
          jewellery_tag: "0",
          harvest: "1",
          tangled: "1",
          parent_id: null,
          name_mtype: "Speed",
        },
        {
          id_mtype: "34",
          poedb_id: "gem",
          jewellery_tag: "0",
          harvest: "0",
          tangled: "1",
          parent_id: null,
          name_mtype: "Gem",
        },
      ],
    },
  ],
  groups: ["2", "1", "8", "11", "12", "13", "9", "14", "10"],
  prefix: [
    {
      id_modifier: "679",
      modgroup: "WeaponCasterDamagePrefix",
      modgroups: '["WeaponCasterDamagePrefix"]',
      affix: "prefix",
      id_mgroup: "2",
      name_modifier: "Socketed Gems are Supported by Level # Cold Penetration, #% increased Cold Damage",
      id_fossil: null,
      mtypes: "|10|7|33|20|34|",
      meta: null,
      mtags: "caster",
      hybrid: "1",
      notable: "0",
      vex: "0",
      amg: null,
      exkey: null,
      ubt: null,
      hr: false,
      ha: false,
      isCraft: false,
      tag: [
        {
          id_mtype: "7",
          poedb_id: "cold",
          jewellery_tag: "0",
          harvest: "1",
          tangled: "1",
          parent_id: "20",
          name_mtype: "Cold",
        },
        {
          id_mtype: "33",
          poedb_id: "damage",
          jewellery_tag: "0",
          harvest: "0",
          tangled: "1",
          parent_id: null,
          name_mtype: "Damage",
        },
        {
          id_mtype: "20",
          poedb_id: "elemental",
          jewellery_tag: "0",
          harvest: "0",
          tangled: "1",
          parent_id: null,
          name_mtype: "Elemental",
        },
        {
          id_mtype: "34",
          poedb_id: "gem",
          jewellery_tag: "0",
          harvest: "0",
          tangled: "1",
          parent_id: null,
          name_mtype: "Gem",
        },
      ],
    },
    {
      id_modifier: "2837",
      modgroup: "LocalAttackReduceEnemyElementalResistance",
      modgroups: '["LocalAttackReduceEnemyElementalResistance"]',
      affix: "prefix",
      id_mgroup: "11",
      name_modifier: "Attacks with this Weapon Penetrate #% Elemental Resistances",
      id_fossil: null,
      mtypes: "|33|20|3|10|21|",
      meta: null,
      mtags: null,
      hybrid: "0",
      notable: "0",
      vex: "0",
      amg: null,
      exkey: null,
      ubt: null,
      hr: true,
      ha: false,
      isCraft: true,
      tag: [
        {
          id_mtype: "33",
          poedb_id: "damage",
          jewellery_tag: "0",
          harvest: "0",
          tangled: "1",
          parent_id: null,
          name_mtype: "Damage",
        },
        {
          id_mtype: "20",
          poedb_id: "elemental",
          jewellery_tag: "0",
          harvest: "0",
          tangled: "1",
          parent_id: null,
          name_mtype: "Elemental",
        },
        {
          id_mtype: "3",
          poedb_id: "attack",
          jewellery_tag: "0",
          harvest: "1",
          tangled: "1",
          parent_id: null,
          name_mtype: "Attack",
        },
      ],
    },
    {
      id_modifier: "2838",
      modgroup: "ChaosPenetrationWithAttacks",
      modgroups: '["ChaosPenetrationWithAttacks"]',
      affix: "prefix",
      id_mgroup: "11",
      name_modifier: "Attacks with this Weapon Penetrate #% Chaos Resistance",
      id_fossil: null,
      mtypes: "|36|33|16|3|21|",
      meta: null,
      mtags: null,
      hybrid: "0",
      notable: "0",
      vex: "0",
      amg: null,
      exkey: null,
      ubt: null,
      hr: true,
      ha: false,
      isCraft: true,
      tag: [
        {
          id_mtype: "33",
          poedb_id: "damage",
          jewellery_tag: "0",
          harvest: "0",
          tangled: "1",
          parent_id: null,
          name_mtype: "Damage",
        },
        {
          id_mtype: "16",
          poedb_id: "chaos",
          jewellery_tag: "0",
          harvest: "1",
          tangled: "1",
          parent_id: null,
          name_mtype: "Chaos",
        },
        {
          id_mtype: "3",
          poedb_id: "attack",
          jewellery_tag: "0",
          harvest: "1",
          tangled: "1",
          parent_id: null,
          name_mtype: "Attack",
        },
      ],
    },
  ],
  suffix: [
    {
      id_modifier: "2369",
      modgroup: "SupportedByAreaProjectile",
      modgroups: '["SupportedByAreaProjectile"]',
      affix: "suffix",
      id_mgroup: "2",
      name_modifier: "Socketed Gems are Supported by Level # Volley, #% increased Projectile Speed",
      id_fossil: null,
      mtypes: "|34|14|",
      meta: null,
      mtags: null,
      hybrid: "1",
      notable: "0",
      vex: "0",
      amg: null,
      exkey: null,
      ubt: null,
      hr: false,
      ha: false,
      isCraft: false,
      tag: [
        {
          id_mtype: "34",
          poedb_id: "gem",
          jewellery_tag: "0",
          harvest: "0",
          tangled: "1",
          parent_id: null,
          name_mtype: "Gem",
        },
        {
          id_mtype: "14",
          poedb_id: "speed",
          jewellery_tag: "0",
          harvest: "1",
          tangled: "1",
          parent_id: null,
          name_mtype: "Speed",
        },
      ],
    },
    {
      id_modifier: "2964",
      modgroup: "ItemGenerationCanHaveMultipleCraftedMods",
      modgroups: '["ItemGenerationCanHaveMultipleCraftedMods"]',
      affix: "suffix",
      id_mgroup: "11",
      name_modifier: "Can have up to 3 Crafted Modifiers",
      id_fossil: null,
      mtypes: "",
      meta: "mul_mods",
      mtags: null,
      hybrid: "0",
      notable: "0",
      vex: "0",
      amg: null,
      exkey: null,
      ubt: null,
      hr: false,
      ha: false,
      isCraft: true,
      tag: [],
    },
    {
      id_modifier: "1762",
      modgroup: "IncreasedAttackSpeed",
      modgroups: '["IncreasedAttackSpeed"]',
      affix: "suffix",
      id_mgroup: "2",
      name_modifier: "Socketed Gems are Supported by Level # Faster Casting, #% increased Cast Speed",
      id_fossil: null,
      mtypes: "|13|14|34|27|",
      meta: null,
      mtags: "caster",
      hybrid: "1",
      notable: "0",
      vex: "0",
      amg: null,
      exkey: null,
      ubt: null,
      hr: false,
      ha: false,
      isCraft: false,
      tag: [
        {
          id_mtype: "13",
          poedb_id: "caster",
          jewellery_tag: "0",
          harvest: "1",
          tangled: "1",
          parent_id: null,
          name_mtype: "Caster",
        },
        {
          id_mtype: "14",
          poedb_id: "speed",
          jewellery_tag: "0",
          harvest: "1",
          tangled: "1",
          parent_id: null,
          name_mtype: "Speed",
        },
        {
          id_mtype: "34",
          poedb_id: "gem",
          jewellery_tag: "0",
          harvest: "0",
          tangled: "1",
          parent_id: null,
          name_mtype: "Gem",
        },
      ],
    },
  ],
};
export const sampleItem2 = {
  "name": "Heathen Wand",
  "quality": "20",
  "crit": "8.00",
  "aps": "1.45",
  "base": [
      "Shaper"
  ],
  "ilevel": 83,
  "implicit": [
      "10% increased Cast Speed"
  ],
  "mods": [
      {
          "id_modifier": "2594",
          "modgroup": "SocketedSpellsDamageFinal",
          "modgroups": "[\"SocketedSpellsDamageFinal\"]",
          "affix": "prefix",
          "id_mgroup": "2",
          "name_modifier": "Socketed Skills deal #% more Spell Damage",
          "id_fossil": null,
          "mtypes": "|33|13|34|27|",
          "meta": null,
          "mtags": "caster",
          "hybrid": "0",
          "notable": "0",
          "vex": "0",
          "amg": null,
          "exkey": null,
          "ubt": null,
          "hr": false,
          "ha": false,
          "isCraft": false,
          "tag": [
              {
                  "id_mtype": "33",
                  "poedb_id": "damage",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Damage"
              },
              {
                  "id_mtype": "13",
                  "poedb_id": "caster",
                  "jewellery_tag": "0",
                  "harvest": "1",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Caster"
              },
              {
                  "id_mtype": "34",
                  "poedb_id": "gem",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Gem"
              }
          ]
      },
      {
          "id_modifier": "679",
          "modgroup": "WeaponCasterDamagePrefix",
          "modgroups": "[\"WeaponCasterDamagePrefix\"]",
          "affix": "prefix",
          "id_mgroup": "2",
          "name_modifier": "Socketed Gems are Supported by Level # Cold Penetration, #% increased Cold Damage",
          "id_fossil": null,
          "mtypes": "|10|7|33|20|34|",
          "meta": null,
          "mtags": "caster",
          "hybrid": "1",
          "notable": "0",
          "vex": "0",
          "amg": null,
          "exkey": null,
          "ubt": null,
          "hr": false,
          "ha": false,
          "isCraft": false,
          "tag": [
              {
                  "id_mtype": "7",
                  "poedb_id": "cold",
                  "jewellery_tag": "0",
                  "harvest": "1",
                  "tangled": "1",
                  "parent_id": "20",
                  "name_mtype": "Cold"
              },
              {
                  "id_mtype": "33",
                  "poedb_id": "damage",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Damage"
              },
              {
                  "id_mtype": "20",
                  "poedb_id": "elemental",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Elemental"
              },
              {
                  "id_mtype": "34",
                  "poedb_id": "gem",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Gem"
              }
          ]
      },
      {
          "id_modifier": "2369",
          "modgroup": "SupportedByAreaProjectile",
          "modgroups": "[\"SupportedByAreaProjectile\"]",
          "affix": "suffix",
          "id_mgroup": "2",
          "name_modifier": "Socketed Gems are Supported by Level # Volley, #% increased Projectile Speed",
          "id_fossil": null,
          "mtypes": "|34|14|",
          "meta": null,
          "mtags": null,
          "hybrid": "1",
          "notable": "0",
          "vex": "0",
          "amg": null,
          "exkey": null,
          "ubt": null,
          "hr": false,
          "ha": false,
          "isCraft": false,
          "tag": [
              {
                  "id_mtype": "34",
                  "poedb_id": "gem",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Gem"
              },
              {
                  "id_mtype": "14",
                  "poedb_id": "speed",
                  "jewellery_tag": "0",
                  "harvest": "1",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Speed"
              }
          ]
      },
      {
          "id_modifier": "684",
          "modgroup": "ColdResistance",
          "modgroups": "[\"ColdResistance\"]",
          "affix": "suffix",
          "id_mgroup": "1",
          "name_modifier": "+#% to Cold Resistance",
          "id_fossil": null,
          "mtypes": "|20|7|35|12|",
          "meta": null,
          "mtags": "",
          "hybrid": "0",
          "notable": "0",
          "vex": "0",
          "amg": null,
          "exkey": null,
          "ubt": null,
          "hr": true,
          "ha": false,
          "isCraft": true,
          "tag": [
              {
                  "id_mtype": "20",
                  "poedb_id": "elemental",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Elemental"
              },
              {
                  "id_mtype": "7",
                  "poedb_id": "cold",
                  "jewellery_tag": "0",
                  "harvest": "1",
                  "tangled": "1",
                  "parent_id": "20",
                  "name_mtype": "Cold"
              },
              {
                  "id_mtype": "35",
                  "poedb_id": "resistance",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Resistance"
              }
          ]
      },
      {
          "id_modifier": "2964",
          "modgroup": "ItemGenerationCanHaveMultipleCraftedMods",
          "modgroups": "[\"ItemGenerationCanHaveMultipleCraftedMods\"]",
          "affix": "suffix",
          "id_mgroup": "11",
          "name_modifier": "Can have up to 3 Crafted Modifiers",
          "id_fossil": null,
          "mtypes": "",
          "meta": "mul_mods",
          "mtags": null,
          "hybrid": "0",
          "notable": "0",
          "vex": "0",
          "amg": null,
          "exkey": null,
          "ubt": null,
          "hr": false,
          "ha": false,
          "isCraft": true,
          "tag": []
      },
      {
          "id_modifier": "2837",
          "modgroup": "LocalAttackReduceEnemyElementalResistance",
          "modgroups": "[\"LocalAttackReduceEnemyElementalResistance\"]",
          "affix": "prefix",
          "id_mgroup": "11",
          "name_modifier": "Attacks with this Weapon Penetrate #% Elemental Resistances",
          "id_fossil": null,
          "mtypes": "|33|20|3|10|21|",
          "meta": null,
          "mtags": null,
          "hybrid": "0",
          "notable": "0",
          "vex": "0",
          "amg": null,
          "exkey": null,
          "ubt": null,
          "hr": true,
          "ha": false,
          "isCraft": true,
          "tag": [
              {
                  "id_mtype": "33",
                  "poedb_id": "damage",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Damage"
              },
              {
                  "id_mtype": "20",
                  "poedb_id": "elemental",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Elemental"
              },
              {
                  "id_mtype": "3",
                  "poedb_id": "attack",
                  "jewellery_tag": "0",
                  "harvest": "1",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Attack"
              }
          ]
      }
  ],
  "groups": [
      "2",
      "1",
      "8",
      "11",
      "12",
      "13",
      "9",
      "14",
      "10"
  ],
  "prefix": [
      {
          "id_modifier": "2594",
          "modgroup": "SocketedSpellsDamageFinal",
          "modgroups": "[\"SocketedSpellsDamageFinal\"]",
          "affix": "prefix",
          "id_mgroup": "2",
          "name_modifier": "Socketed Skills deal #% more Spell Damage",
          "id_fossil": null,
          "mtypes": "|33|13|34|27|",
          "meta": null,
          "mtags": "caster",
          "hybrid": "0",
          "notable": "0",
          "vex": "0",
          "amg": null,
          "exkey": null,
          "ubt": null,
          "hr": false,
          "ha": false,
          "isCraft": false,
          "tag": [
              {
                  "id_mtype": "33",
                  "poedb_id": "damage",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Damage"
              },
              {
                  "id_mtype": "13",
                  "poedb_id": "caster",
                  "jewellery_tag": "0",
                  "harvest": "1",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Caster"
              },
              {
                  "id_mtype": "34",
                  "poedb_id": "gem",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Gem"
              }
          ]
      },
      {
          "id_modifier": "679",
          "modgroup": "WeaponCasterDamagePrefix",
          "modgroups": "[\"WeaponCasterDamagePrefix\"]",
          "affix": "prefix",
          "id_mgroup": "2",
          "name_modifier": "Socketed Gems are Supported by Level # Cold Penetration, #% increased Cold Damage",
          "id_fossil": null,
          "mtypes": "|10|7|33|20|34|",
          "meta": null,
          "mtags": "caster",
          "hybrid": "1",
          "notable": "0",
          "vex": "0",
          "amg": null,
          "exkey": null,
          "ubt": null,
          "hr": false,
          "ha": false,
          "isCraft": false,
          "tag": [
              {
                  "id_mtype": "7",
                  "poedb_id": "cold",
                  "jewellery_tag": "0",
                  "harvest": "1",
                  "tangled": "1",
                  "parent_id": "20",
                  "name_mtype": "Cold"
              },
              {
                  "id_mtype": "33",
                  "poedb_id": "damage",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Damage"
              },
              {
                  "id_mtype": "20",
                  "poedb_id": "elemental",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Elemental"
              },
              {
                  "id_mtype": "34",
                  "poedb_id": "gem",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Gem"
              }
          ]
      },
      {
          "id_modifier": "2837",
          "modgroup": "LocalAttackReduceEnemyElementalResistance",
          "modgroups": "[\"LocalAttackReduceEnemyElementalResistance\"]",
          "affix": "prefix",
          "id_mgroup": "11",
          "name_modifier": "Attacks with this Weapon Penetrate #% Elemental Resistances",
          "id_fossil": null,
          "mtypes": "|33|20|3|10|21|",
          "meta": null,
          "mtags": null,
          "hybrid": "0",
          "notable": "0",
          "vex": "0",
          "amg": null,
          "exkey": null,
          "ubt": null,
          "hr": true,
          "ha": false,
          "isCraft": true,
          "tag": [
              {
                  "id_mtype": "33",
                  "poedb_id": "damage",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Damage"
              },
              {
                  "id_mtype": "20",
                  "poedb_id": "elemental",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Elemental"
              },
              {
                  "id_mtype": "3",
                  "poedb_id": "attack",
                  "jewellery_tag": "0",
                  "harvest": "1",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Attack"
              }
          ]
      }
  ],
  "suffix": [
      {
          "id_modifier": "2369",
          "modgroup": "SupportedByAreaProjectile",
          "modgroups": "[\"SupportedByAreaProjectile\"]",
          "affix": "suffix",
          "id_mgroup": "2",
          "name_modifier": "Socketed Gems are Supported by Level # Volley, #% increased Projectile Speed",
          "id_fossil": null,
          "mtypes": "|34|14|",
          "meta": null,
          "mtags": null,
          "hybrid": "1",
          "notable": "0",
          "vex": "0",
          "amg": null,
          "exkey": null,
          "ubt": null,
          "hr": false,
          "ha": false,
          "isCraft": false,
          "tag": [
              {
                  "id_mtype": "34",
                  "poedb_id": "gem",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Gem"
              },
              {
                  "id_mtype": "14",
                  "poedb_id": "speed",
                  "jewellery_tag": "0",
                  "harvest": "1",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Speed"
              }
          ]
      },
      {
          "id_modifier": "684",
          "modgroup": "ColdResistance",
          "modgroups": "[\"ColdResistance\"]",
          "affix": "suffix",
          "id_mgroup": "1",
          "name_modifier": "+#% to Cold Resistance",
          "id_fossil": null,
          "mtypes": "|20|7|35|12|",
          "meta": null,
          "mtags": "",
          "hybrid": "0",
          "notable": "0",
          "vex": "0",
          "amg": null,
          "exkey": null,
          "ubt": null,
          "hr": true,
          "ha": false,
          "isCraft": true,
          "tag": [
              {
                  "id_mtype": "20",
                  "poedb_id": "elemental",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Elemental"
              },
              {
                  "id_mtype": "7",
                  "poedb_id": "cold",
                  "jewellery_tag": "0",
                  "harvest": "1",
                  "tangled": "1",
                  "parent_id": "20",
                  "name_mtype": "Cold"
              },
              {
                  "id_mtype": "35",
                  "poedb_id": "resistance",
                  "jewellery_tag": "0",
                  "harvest": "0",
                  "tangled": "1",
                  "parent_id": null,
                  "name_mtype": "Resistance"
              }
          ]
      },
      {
          "id_modifier": "2964",
          "modgroup": "ItemGenerationCanHaveMultipleCraftedMods",
          "modgroups": "[\"ItemGenerationCanHaveMultipleCraftedMods\"]",
          "affix": "suffix",
          "id_mgroup": "11",
          "name_modifier": "Can have up to 3 Crafted Modifiers",
          "id_fossil": null,
          "mtypes": "",
          "meta": "mul_mods",
          "mtags": null,
          "hybrid": "0",
          "notable": "0",
          "vex": "0",
          "amg": null,
          "exkey": null,
          "ubt": null,
          "hr": false,
          "ha": false,
          "isCraft": true,
          "tag": []
      }
  ]
}

// Rarity: Rare
// Crafted Item
// Heathen Wand
// --------
// Quality: +20% (augmented)
// Physical Damage: 33-62
// Critical Strike Chance: 8.00%
// Attacks Per Second: 1.62
// --------
// Requirements:
// Int: 184
// Level: 55
// --------
// Item Level: 83
// --------
// 10% increased Cast Speed (implicit)
// --------
// Socketed Gems are Supported by Level 20 Cold Penetration
// 58% increased Cold Damage
// Socketed Gems are Supported by Level 20 Volley
// 25% increased Projectile Speed
// Can have up to 3 Crafted Modifiers (crafted)
// Attacks with this Weapon Penetrate 11% Elemental Resistances (crafted)
// Socketed Gems are Supported by Level 20 Faster Attacks
// 12% increased Attack Speed
// Attacks with this Weapon Penetrate 12% Chaos Resistance (crafted)
// --------
// Shaper Item
